gitlab:
  image: 'gitlab/gitlab-ee:latest'
  restart: always
  hostname: ${GITLAB_HOSTNAME}
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url ${GITLAB_HOSTNAME}
  ports:
    - ${GITLAB_PORT}:80
    - ${GITLAB_HTTPS_PORT}:443
    - ${GITLAB_SSH_PORT}:22
  volumes:
    - ${GITLAB_ETC_DIR}:/etc/gitlab
    - ${GITLAB_LOG_DIR}:/var/log/gitlab
    - ${GITLAB_DATA_DIR}:/var/opt/gitlab


